/** @format */

export const EventActionTypes = {
  SET_CURRENT_EVENT: 'SET_CURRENT_EVENT',
  SET_ACTIVE_EVENT: 'SET_ACTIVE_EVENT',
  SET_COMPONENT_VALUES: 'SET_COMPONENT_VALUES',
  SET_EVENT_LISTENER: 'SET_EVENT_LISTENER',
  SET_SPRITE_LISTENER_STATUS: 'SET_SPRITE_LISTENER_STATUS',
  SET_FLAG_LISTENER_STATUS: 'SET_FLAG_LISTENER_STATUS',
};
